# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FeishuDocsCli < Formula
  desc "飞书文档与知识库 CLI 管理工具"
  homepage "https://github.com/KQAR/feishu-docs-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.0/feishu-docs-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "65f8a37f50e86d679594176d70ac4c7eee496cbd195862df406ddcfb4cf2caed"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.0/feishu-docs-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "73a24d2a8825389122f9f8fb9e3f8141b3fda87f3412159817fc2c2565eecd11"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.0/feishu-docs-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "a8fd04e90359c45ae23ef2fda41ed8846c8094328e7e655bf9f951ae1d06ea77"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.0/feishu-docs-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "bb9927c9b417714286fbaf511d0bc79051dfacf8f6dd46623ccd642ec7761988"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  test do
    system "#{bin}/feishu-docs-cli", "version"
  end
end
