# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FeishuDocs < Formula
  desc "飞书文档与知识库 CLI 管理工具"
  homepage "https://github.com/KQAR/feishu-docs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KQAR/feishu-docs/releases/download/v0.1.0/feishu-docs_0.1.0_darwin_amd64.tar.gz"
      sha256 "18d00bd34e9608acd2645b80451976ede0f14ff54e9c1a3330fe1e4c9b42ed63"

      define_method(:install) do
        bin.install "feishu-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KQAR/feishu-docs/releases/download/v0.1.0/feishu-docs_0.1.0_darwin_arm64.tar.gz"
      sha256 "26952c59220e1308031f55e2aac6b94da0a40a5d26dfe629bd7a6af73ab3ee30"

      define_method(:install) do
        bin.install "feishu-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs/releases/download/v0.1.0/feishu-docs_0.1.0_linux_amd64.tar.gz"
      sha256 "d041f9960b79b3eb317a76c387dfdba82b772576ff2c4f4cb6ce893fa987199c"
      define_method(:install) do
        bin.install "feishu-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs/releases/download/v0.1.0/feishu-docs_0.1.0_linux_arm64.tar.gz"
      sha256 "99a38d130fc15a8012e5b31551aca393fb5326e233e22a05abd68820f41a9927"
      define_method(:install) do
        bin.install "feishu-docs"
      end
    end
  end

  test do
    system "#{bin}/feishu-docs", "version"
  end
end
