# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FeishuDocsCli < Formula
  desc "飞书文档与知识库 CLI 管理工具"
  homepage "https://github.com/KQAR/feishu-docs-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.3.0/feishu-docs-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "aa52f4f9edc9591907754e2e328979e243bf6ded67cb28605d5516a005a47b9b"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.3.0/feishu-docs-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "8aa24194e0a836754ef46cd01c86ff79090ad65da46f5adc91935d2e9a2949ac"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.3.0/feishu-docs-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "73d7856a8ca2c31dc725a95caefc4177b99cd3af682e5a7161bbebc410f726a3"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.3.0/feishu-docs-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "38587b0802e9a0ef2c9e4162c87a0547645120431c0b3939a6cde61e2b4130a3"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  test do
    system "#{bin}/feishu-docs-cli", "version"
  end
end
