# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FeishuDocsCli < Formula
  desc "飞书文档与知识库 CLI 管理工具"
  homepage "https://github.com/KQAR/feishu-docs-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.1/feishu-docs-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "6c1bca7502dc333959bbbe92853ea5503e7b896bf5983e441e0e0544d440a4a3"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.1/feishu-docs-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "449974009eceb6ae5d42c80835223d6eb61d27c58b600910d290ad0159018da8"

      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.1/feishu-docs-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "7169a84f4ff1f97c5fc712bb9b4d137276acaf23ed1ebc71be9aaa4d796db034"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KQAR/feishu-docs-cli/releases/download/v0.4.1/feishu-docs-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "4ae6ffc7751ac76006d43739a2aaa137bd520c79c373accda554d1fb35c263bc"
      define_method(:install) do
        bin.install "feishu-docs-cli"
      end
    end
  end

  test do
    system "#{bin}/feishu-docs-cli", "version"
  end
end
